name: 'First issue greeter'
description: 'Greets issuer when the first issue to a repo is made'
author: 'JJ'
branding:
  icon: aperture
  color: green
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  greeting:
    description: 'Comment to post on an individuals first pull request'
runs:
  using: 'node12'
  main: 'lib/main.js'
