name: 'First PR greeter'
description: 'Greets when the first PR is made'
author: 'JJ'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  pr-message:
    description: 'Comment to post on an individuals first pull request'
runs:
  using: 'node12'
  main: 'lib/main.js'
